export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_ROBOTS = {
    PENDING: 'REQUEST_ROBOTS_PENDING',
    SUCCESS: 'REQUEST_ROBOTS_SUCCESS',
    FAILED: 'REQUEST_ROBOTS_FAILED'
}